import os
import traceback
from contextlib import asynccontextmanager
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi import Request
from fastapi.responses import JSONResponse
from fastapi.exceptions import RequestValidationError

from pydantic import BaseModel, Field
import uvicorn
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.messages import BaseMessage, HumanMessage, SystemMessage, AIMessage
from langgraph.graph import StateGraph, END
from langgraph.prebuilt import ToolNode
from langgraph.prebuilt import tools_condition
from langgraph.checkpoint.memory import MemorySaver
from langchain_core.runnables import RunnableConfig

from state import DMState, QAResult
from prompts import MASTER_PROMPT
from vault_io import write_audit_log, upsert_journal_section, initialize_engine_from_vault, sync_engine_to_vault
from tools import *
from tools import _get_config_tone

import time

# Define the master list of tools ONCE so it's consistent
MASTER_TOOLS_LIST = [
    upsert_journal_section, create_new_entity, flesh_out_entity, update_yaml_frontmatter, 
    equip_item, use_expendable_resource, fetch_entity_context, level_up_character, 
    update_character_status, manage_inventory, roll_generic_dice, perform_ability_check_or_save, search_vault_by_tag, 
    advance_time, start_combat, update_combat_state, end_combat, execute_melee_attack, 
    modify_health, query_bestiary, query_rulebook, query_campaign_module,
    use_ability_or_spell, encode_new_compendium_entry
]

# 1. INITIALIZE THE APP FIRST
# This is handled by the lifespan manager further down

# GLOBAL STATE
dm_engine_app = None  
draft_llm = None
qa_llm = None



# 5. CODE
# 5.1. THE PLANNER NODE

# --- REPLACE YOUR EXISTING GRAPH NODES AND BUILDER WITH THIS ---

async def planner_node(state: DMState, config: RunnableConfig):
    sys_msg = SystemMessage(content="""
        You are the D&D Tactical Planner. You are invisible to the player.
        Your ONLY job is to translate the player's intent into Tool Calls.
        
        TOOL ROUTING GUIDE:
        1. MELEE WEAPONS: Always use `execute_melee_attack`. Never roll manually.
        2. SPELLS & CLASS FEATURES: Always use `use_ability_or_spell`. Never roll manually.
        3. SKILL CHECKS & SAVES: Use `perform_ability_check_or_save` for jumping, sneaking, perception, etc.
        4. DAMAGE/HEALING: Use `modify_health` for falling damage, trap damage, or drinking potions.
        
        If you get a CACHE MISS on a spell or ability, use `query_rulebook` to find the rules, 
        then `encode_new_compendium_entry` to permanently save it to the engine.
        
        Once all tool logic is complete and you have the "MECHANICAL TRUTH", 
        output a brief summary of the events. DO NOT write dialogue or narrative prose.
        """)    
    llm_with_tools = draft_llm.bind_tools(MASTER_TOOLS_LIST)
    response = await llm_with_tools.ainvoke([sys_msg] + state["messages"], config=config)
    return {"messages": [response]}

async def narrator_node(state: DMState, config: RunnableConfig):
    """The Storyteller. Turns the mechanical truth into vivid prose."""
    
    # 1. Check if we are in a revision loop
    feedback_context = ""
    if state.get("qa_feedback") and state["qa_feedback"] != "APPROVED":
        feedback_context = f"\n\n[QA REJECTION FEEDBACK]: Your previous draft was rejected for the following reason:\n{state['qa_feedback']}\nFix this in your new draft."

    sys_msg = SystemMessage(content=f"""
    You are the Dungeon Master. Read the history of the current interaction.
    Look at the 'MECHANICAL TRUTH' outputs generated by the system tools.
    Narrate these exact events vividly to the player. 
    DO NOT change the numbers, damage, or hit/miss outcomes. Do not roll dice.
    Output only the narrative response.
    Do not violate player agency or do anything more than add color to an action dialogue that the player dictated. {feedback_context}
    """)
    
    # Invoke WITHOUT tools so it is forced to write a string
    response = await draft_llm.ainvoke([sys_msg] + state["messages"], config=config)
    return {"draft_response": response.content}

def build_graph():
    workflow = StateGraph(DMState)

    workflow.add_node("planner", planner_node)
    
    # ADD YOUR OTHER TOOLS HERE
    workflow.add_node("action", ToolNode(MASTER_TOOLS_LIST))
    
    workflow.add_node("narrator", narrator_node)
    workflow.add_node("qa", qa_node)

    workflow.set_entry_point("planner")
    workflow.add_conditional_edges("planner", tools_condition, {"tools": "action", "__end__": "narrator"})
    workflow.add_edge("action", "planner")
    workflow.add_edge("narrator", "qa")
    workflow.add_conditional_edges("qa", qa_router)

    return workflow.compile(checkpointer=MemorySaver())


from langchain_core.messages import ToolMessage # Make sure to import this at the top!

async def qa_node(state: DMState, config: RunnableConfig):
    global qa_llm
    vault, draft, revisions = state["vault_path"], state["draft_response"], state.get("revision_count", 0)
    
    # --- ESCAPE CLAUSE 1: Allow DM to ask questions without being audited ---
    if draft.strip().startswith("[OOC") or draft.strip().startswith("OOC:"):
        await write_audit_log(vault, "QA Agent", "Bypass", "OOC Clarification detected. Auto-approving.")
        return {"qa_feedback": "APPROVED"}
    
    # --- ESCAPE CLAUSE 2: Max Revisions ---
    if revisions >= 3:
        await write_audit_log(vault, "QA Agent", "Force Approve", "Max revisions reached. Passing to prevent loop.")
        return {"qa_feedback": "APPROVED"}

    # --- GATHER CONTEXT (Tools & Mechanical Truths) ---
    recent_tools = []
    mechanical_truths = []
    
    # Iterate backwards to find everything that happened THIS turn
    for msg in reversed(state["messages"]):
        # Stop searching when we hit the player's actual prompt
        if isinstance(msg, HumanMessage) and not msg.content.startswith("[SYSTEM OVERRIDE"): 
            break 
            
        if hasattr(msg, "tool_calls") and msg.tool_calls:
            for tc in msg.tool_calls:
                recent_tools.append(f"{tc['name']}({tc.get('args', {})})")
                
        # NEW: Grab the math results from the deterministic engine!
        if isinstance(msg, ToolMessage) and "MECHANICAL TRUTH" in msg.content:
            mechanical_truths.append(msg.content)
                
    tools_used_str = " | ".join(recent_tools) if recent_tools else "None"
    truth_str = "\n".join(mechanical_truths) if mechanical_truths else "No combat math was executed this turn."
    
    await write_audit_log(vault, "QA Agent", "Reviewing Draft", f"Tools audited this turn: {tools_used_str}")
    
    # --- TONE CHECKING ---
    try:
        from tools import _get_config_tone
        tone_rules = _get_config_tone(vault)
    except Exception:
        tone_rules = ""
    tone_check = f"10. TONE & BOUNDARIES: Did the DM violate any of these boundaries: '{tone_rules}'? (If yes, REJECT).\n" if tone_rules else ""

    # --- THE SUPER-PROMPT (Merged Old + New) ---
    qa_prompt = (
        "You are the strict QA Auditor for a D&D game. Review this DM Draft:\n"
        f"DRAFT: '{draft}'\n"
        f"TOOLS USED THIS TURN: {tools_used_str}\n"
        f"ENGINE MECHANICAL TRUTHS:\n{truth_str}\n\n"
        "RULES COMPLIANCE CHECKLIST:\n"
        "1. MECHANICAL SYNC: Did the draft contradict the ENGINE MECHANICAL TRUTHS? (e.g., Engine says MISS, draft says HIT; Engine says 8 damage, draft says 10). (If yes, REJECT).\n"
        "2. PLAYER AGENCY: Did the DM dictate, as opposed to minor embellishment, what the player's character thinks, their emotions, or their actions? (If yes, REJECT).\n"
        "3. DESCRIBE TO ME: Did the DM state factual NPC motives (e.g., 'He is lying') instead of physical sensory details? (If yes, REJECT).\n"
        "4. META-GAMING: Did the DM leak mechanical stats like exact AC, HP numbers, or DCs in the narrative? (If yes, REJECT).\n"
        "5. FAIL FORWARD: If an action failed, did the DM introduce a complication rather than a dead end? (If yes, REJECT).\n"
        "6. DICE MATH AUDIT: Did the DM hallucinate any dice rolls or damage that do not appear in the Tools Used or Mechanical Truths? (If yes, REJECT).\n"
        "7. FEATS & MECHANICS: Did the DM ignore a character's active feats or spells during combat/checks? (If yes, REJECT).\n"
        "8. MAGIC ITEMS & ATTUNEMENT: Did the DM grant/use an item without tracking it, or allow exceeding 3 attuned items? (If yes, REJECT).\n"
        "9. OBSIDIAN FORMATTING: Did the DM fail to use [[Wikilinks]] for proper nouns? (If yes, REJECT).\n"
        + tone_check +
        "\nIf ANY rule is broken, set 'approved' to False and explain exactly what to rewrite. "
        "If the DM applied a mechanic incorrectly, do not just tell them it is wrong. You MUST provide the details of the game rules needed to fix it."
    )
    
    # We use structured output to enforce the QAResult schema
    qa_chain = qa_llm.with_structured_output(QAResult)
    
    try:
        result: QAResult = await qa_chain.ainvoke([HumanMessage(content=qa_prompt)], config=config)
    except Exception as e:
        print(f"[QA Agent] Error during structured output parsing: {e}. Auto-approving.")
        return {"qa_feedback": "APPROVED"}
    
    # --- QA INTERCEPT: QA takes over and asks the player directly ---
    if getattr(result, 'requires_clarification', False):
        await write_audit_log(vault, "QA Agent", "Clarification Intercept", result.clarification_message)
        return {
            "draft_response": f"**[OOC - Engine Supervisor]:** {result.clarification_message}", 
            "qa_feedback": "APPROVED" # Approving it forces the graph to end and output this clarification
        }
    
    elif result.approved:
        await write_audit_log(vault, "QA Agent", "Result", "APPROVED")
        return {"qa_feedback": "APPROVED"}
    
    else:
        await write_audit_log(vault, "QA Agent", "Result", f"REJECTED. Feedback: {result.feedback}")
        
        # We append a HumanMessage directly to the state's message array, just like your old code!
        rejection_msg = HumanMessage(
            content=f"[SYSTEM OVERRIDE - QA REJECTION]: {result.feedback}\n\nYou MUST rewrite your response to fix these explicit errors immediately. DO NOT apologize, DO NOT acknowledge the error, and DO NOT break character. Simply output the newly corrected narrative."
        )
        
        return {
            "qa_feedback": result.feedback, 
            "revision_count": revisions + 1,
            "messages": [rejection_msg]
        }
 

def qa_router(state: DMState) -> str:
    # If approved, we are done!
    if state.get("qa_feedback") == "APPROVED":
        return END
        
    # Prevent infinite loops. If it fails 3 times, force it to END anyway.
    if state.get("revision_count", 0) >= 3:
        print("[QA Agent] - Max revisions reached. Force approving.")
        return END
        
    # If rejected and under the limit, send it back to the Narrator to rewrite
    return "narrator"

@asynccontextmanager
async def lifespan(app: FastAPI):
    global dm_engine_app, draft_llm, qa_llm
    
    try:
        # Upgraded to Pro for deeper reasoning, and Temp 0.6 to encourage "Jazz"
        draft_llm = ChatGoogleGenerativeAI(model="gemini-2.5-pro", temperature=0.6)
        
        # Build and compile the multi-agent graph ONCE when the server boots
        dm_engine_app = build_graph()
        
        print("DM Engine initialized successfully with ReAct architecture.")
        yield
    except Exception as e:
        print(f"Failed to initialize DM Engine: {e}")
        yield
        
# --- 4. YOUR FAST API APP ---
app = FastAPI(title="AI DM Engine", lifespan=lifespan)

# ADD CORS MIDDLEWARE (Crucial for Obsidian to connect!)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], 
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# EXCEPTION HANDLERS
@app.exception_handler(RequestValidationError)
async def validation_exception_handler(request: Request, exc: RequestValidationError):
    print("\n" + "!"*40)
    print("🚨 BAD PAYLOAD RECEIVED FROM FRONTEND 🚨")
    print(f"Details: {exc.errors()}")
    print("!"*40 + "\n")
    return JSONResponse(
        status_code=422,
        content={"detail": exc.errors(), "body": exc.body},
    )

@app.exception_handler(Exception)
async def global_exception_handler(request: Request, exc: Exception):
    print("\n" + "💥"*20)
    print("💥 UNHANDLED SERVER EXCEPTION 💥")
    traceback.print_exc()
    print("💥"*20 + "\n")
    return JSONResponse(
        status_code=500,
        content={"detail": "Internal Server Error. Check the backend console."},
    )

@app.middleware("http")
async def log_requests(request: Request, call_next):
    start_time = time.time()
    print(f"\n---> Incoming Request: {request.method} {request.url}")
    
    try:
        response = await call_next(request)
        process_time = time.time() - start_time
        print(f"<--- Response: {response.status_code} (Took {process_time:.2f}s)")
        return response
    except Exception as e:
        print(f"<--- Server Error: {str(e)}")
        raise

class ChatRequest(BaseModel):
    message: str
    character: str
    vault_path: str

class ChatResponse(BaseModel):
    reply: str
    status: str

@app.post("/chat", response_model=ChatResponse)
async def chat_endpoint(request: ChatRequest): # <--- Added async
    global dm_engine_app
    if not dm_engine_app: raise HTTPException(status_code=500, detail="DM Engine not initialized.")
    
    clean_msg = request.message[1:].strip() if request.message.startswith(">") else request.message
    prefix = f"[OOC Question from {request.character}]:" if request.message.startswith(">") else f"[{request.character} acts/speaks]:"
    formatted_prompt = f"{prefix} {clean_msg}"

    print(f"\nInitiating Supervisor Loop for: {formatted_prompt}")
    await write_audit_log(request.vault_path, request.character, "Input Received", clean_msg)
    
    initial_state = {
        "messages": [HumanMessage(content=formatted_prompt)],
        "vault_path": request.vault_path,
        "active_character": request.character,
        "draft_response": "",
        "qa_feedback": "",
        "revision_count": 0
    }
    
    config = {"configurable": {"thread_id": request.vault_path}}

    try:
        # NEW: Initialize the Deterministic Engine from Obsidian before we start thinking
        await initialize_engine_from_vault(request.vault_path)

        # NEW: Await the asynchronous invocation!
        final_state = await dm_engine_app.ainvoke(initial_state, config=config)
        
        # NEW: Save the results of any combat math back to Obsidian files
        await sync_engine_to_vault()
        
        return ChatResponse(reply=final_state["draft_response"], status="success")
        
    except Exception as e:
        print("\n" + "="*40 + "\n💥 FATAL ERROR DURING SUPERVISOR EXECUTION 💥\n" + "="*40)
        traceback.print_exc()
        print("="*40 + "\n")
        raise HTTPException(status_code=500, detail=str(e))

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)

